pipeline:
  docker:
    image: plugins/docker
    repo: samuelph/feed2toot
    tags: latest
    when:
      branch:
        - main
      event:
        - push
  cr:
    image: plugins/docker
    registry: cr.sp-codes.de
    repo: cr.sp-codes.de/samuel-p/feed2toot
    tags: latest
    when:
      branch:
        - main
      event:
        - push
